"""
Demo: MCNP 6.3 Compatibility Test

This script demonstrates that mcnptoolspro works correctly with PTRAC files
generated by MCNP 6.3, showing detailed event information for each filter type.

Usage:
    python demo_mcnp63_compatibility.py [filter_type]

If no filter is specified, tests all available filters.

Examples:
    python demo_mcnp63_compatibility.py              # Test all filters
    python demo_mcnp63_compatibility.py none         # Test filter_none only
    python demo_mcnp63_compatibility.py event        # Test filter_event only
"""

import sys
from pathlib import Path
from collections import OrderedDict

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent / 'python'))

import mcnptoolspro as m

# Event type labels
event_base_labels = {
    1000: "SRC", 2000: "BNK", 2030: "BNK*", 3000: "SUR",
    4000: "COL", 5000: "TER", 9000: "LST"
}

# PTRAC data field codes (subset for display)
ptrac_data_fields = OrderedDict([
    (16, "PARTICLE"), (17, "CELL"), (18, "MATERIAL"),
    (20, "X"), (21, "Y"), (22, "Z"),
    (23, "U"), (24, "V"), (25, "W"),
    (26, "ENERGY"), (27, "WEIGHT"), (28, "TIME")
])

# Particle type labels
particle_labels = {
    1: "NEUTRON", 2: "PHOTON", 3: "ELECTRON", 4: "POSITRON",
    5: "PROTON", 6: "DEUTERON", 7: "TRITON", 8: "HELIUM3",
    9: "ALPHA", 10: "HEAVY_ION", 11: "CHARGED", 12: "NEUTRAL"
}

# Test files (MCNP 6.3)
test_files = {
    'none': '../tests/test_data_github/ptrac63_filter_none_ASC.ip',
    'event': '../tests/test_data_github/ptrac63_filter_event_ASC.ip',
    'type': '../tests/test_data_github/ptrac63_filter_type_ASC.ip',
    'filter': '../tests/test_data_github/ptrac63_filter_filter_ASC.ip',
    'tally': '../tests/test_data_github/ptrac63_filter_tally_ASC.ip',
    'all': '../tests/test_data_github/ptrac63_filter_all_ASC.ip',
}


def analyze_filter(filter_name, file_path):
    """Analyze a single PTRAC file and display detailed information"""

    full_path = Path(__file__).parent / file_path

    if not full_path.exists():
        return {'error': f'File not found: {file_path}'}

    print(f"\n{'=' * 80}")
    print(f"FILTER: {filter_name.upper()}")
    print(f"File: {full_path.name}")
    print(f"{'=' * 80}")

    try:
        # Open PTRAC file
        ptrac = m.Ptrac(str(full_path), m.Ptrac.ASC_PTRAC)

        # Read first history only
        histories = ptrac.ReadHistories(1)

        if len(histories) == 0:
            print("  [ERROR] No histories found in file")
            return {'error': 'No histories'}

        hist = histories[0]
        num_events = hist.GetNumEvents()

        print(f"\nHistory Statistics:")
        print(f"  Number of events: {num_events}")

        # Count event types
        event_types = {}
        for i in range(num_events):
            event = hist.GetEvent(i)
            evt_type = event.Type()
            base_type = (evt_type // 1000) * 1000
            event_types[base_type] = event_types.get(base_type, 0) + 1

        print(f"  Event types: ", end="")
        type_strs = []
        for evt_type in sorted(event_types.keys()):
            count = event_types[evt_type]
            name = event_base_labels.get(evt_type, f'TYPE_{evt_type}')
            type_strs.append(f'{name}:{count}')
        print(', '.join(type_strs))

        # Display first 3 events in detail
        print(f"\nDetailed Event Information (first 3 events):")
        print("-" * 80)

        max_display = min(3, num_events)
        for i in range(max_display):
            event = hist.GetEvent(i)
            evt_type = event.Type()
            base_code = (evt_type // 1000) * 1000
            base_label = event_base_labels.get(base_code, f"UNKNOWN({evt_type})")

            print(f"\n  Event #{i+1}: {base_label} (type {evt_type})")

            # Display key fields
            for field_code, field_label in ptrac_data_fields.items():
                if event.Has(field_code):
                    val = event.Get(field_code)

                    if field_label == "PARTICLE":
                        particle_name = particle_labels.get(int(val), f"UNKNOWN({int(val)})")
                        print(f"    {field_label:12s} = {int(val):3d} ({particle_name})")
                    elif field_label in ["X", "Y", "Z", "U", "V", "W", "ENERGY", "WEIGHT", "TIME"]:
                        print(f"    {field_label:12s} = {val:.6e}")
                    elif field_label in ["CELL", "MATERIAL"]:
                        print(f"    {field_label:12s} = {int(val)}")
                    else:
                        print(f"    {field_label:12s} = {val}")

        if num_events > max_display:
            print(f"\n  ... and {num_events - max_display} more events")

        return {'success': True, 'num_events': num_events, 'event_types': event_types}

    except Exception as e:
        print(f"  [ERROR] {str(e)}")
        return {'error': str(e)}


def main():
    print("=" * 80)
    print("MCNP 6.3 COMPATIBILITY DEMONSTRATION")
    print("=" * 80)
    print("\nThis demo shows that mcnptoolspro correctly parses PTRAC files")
    print("generated by MCNP 6.3, displaying detailed event information.")
    print()

    # Determine which filters to test
    if len(sys.argv) > 1:
        filter_name = sys.argv[1].lower()
        if filter_name not in test_files:
            print(f"ERROR: Unknown filter '{filter_name}'")
            print(f"Available filters: {', '.join(test_files.keys())}")
            return 1
        filters_to_test = {filter_name: test_files[filter_name]}
    else:
        filters_to_test = test_files

    # Test each filter
    results = {}
    for filter_name, file_path in filters_to_test.items():
        result = analyze_filter(filter_name, file_path)
        results[filter_name] = result

    # Summary
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)

    success_count = 0
    for filter_name, result in results.items():
        if 'error' not in result:
            status = "[OK]"
            success_count += 1
            num_events = result['num_events']
            print(f"  {status} {filter_name:10s}: {num_events} events parsed successfully")
        else:
            status = "[FAIL]"
            print(f"  {status} {filter_name:10s}: {result['error']}")

    print()
    if success_count == len(results):
        print("[SUCCESS] All MCNP 6.3 filters work correctly!")
    else:
        print(f"[PARTIAL] {success_count}/{len(results)} filters working")

    print("=" * 80)

    return 0 if success_count == len(results) else 1


if __name__ == '__main__':
    sys.exit(main())
